# Generated by Django 3.0.8 on 2020-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Past_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField()),
                ('branch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Opp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=100)),
                ('gen_date', models.DateField()),
                ('past', models.ManyToManyField(to='login.Past_scholars')),
            ],
        ),
    ]
